### ISSUE TITLE
No such module 'Argo'

### ISSUE THREAD

**Issue by XavierLost** [kickstarter/ios-oss#1006]

**Comment by plam4u** [comment]
### What worked for me:
1. make sure you're using Xcode 10 because some of the libraries require Swift 5.0. There is a branch called "xcode-11" which is migrating the project to Xcode 11, but for now use Xcode 10.
2. run `carthage bootstrap --platform iOS --cache-builds`. This will take several minutes. It is assuming you have Carthage installed.
3. profit 🎉

**Comment by jsdev887** [comment]
Same problem! Also I tried the way @plam4u did but it didn't work for me.
Any solution??

**Comment by nagashreeabhilash100** [comment]
Running into same issue. Getting No such module 'Argo'. I tried with Xcode 10.3 & 11.2.1, did not work for me.

**Comment by justinswart** [comment]
Thanks @plam4u, that's correct we're currently migrating everything to compile in Xcode 11 and hope to have that branch merged soon. For now you can follow @plam4u's steps above using Xcode 11.3. Also try deleting the `Carthage` folder and running that command again to be sure that the deps are rebuilt.

**Comment by justinswart** [comment]
Our `master` branch is now updated to support Xcode 11 👍
