### ISSUE TITLE
huge .git directory size, try a "repack"

### ISSUE THREAD

**Issue by SeanFelipe** [kickstarter/ios-oss#1100]
Hello Kickstarters, 

I was poking around your android + ios code. The android code is reasonable in size but the ios repo is ... 2.1  gigs ! Doing a little checking, I see that 1.9 G of that is in your `/.git` directory .

You've probably checked in some binary files and the .git directory is thrashing the deltas. You can repack the .git directory and dramatically reduce repo size:
https://stackoverflow.com/questions/5613345/how-to-shrink-the-git-folder

```
✔ ~/p/Kickstarter/ios-oss/.git 
21:06 $ du -h .
1.9G	./objects/pack
  0B	./objects/info
1.9G	./objects
4.0K	./info
4.0K	./logs/refs/heads
4.0K	./logs/refs/remotes/origin
4.0K	./logs/refs/remotes
8.0K	./logs/refs
 12K	./logs
 48K	./hooks
4.0K	./refs/heads
  0B	./refs/tags
4.0K	./refs/remotes/origin
4.0K	./refs/remotes
8.0K	./refs
1.9G	.
```

**Comment by justinswart** [comment]
Hi @SeanFelipe, thanks for the suggestion. We're not too concerned about the size of the repo at this stage, storage is cheap and the internet is fast 😄. It's big because we record snapshot tests for almost all of our UI. Some in multiple languages and sizes so it does add up.

We'll consider pruning some history if it ever becomes a problem 👍
