### ISSUE TITLE
Question about architecture and bindings

### ISSUE THREAD

**Issue by lifetimelearn3r** [kickstarter/ios-oss#1324]
Hi,

I really appreciate the team for making the project open source. It really helps a newcomer to MVVM and FRP like me, to explore potential architecture designs. Much love! ❤️ 

Having said that, I have a few questions regarding the architecture and bindings.

1. I saw that the 'input signals' `*ViewModelInput` is always a `func`. Wouldn't it be cleaner (in terms of organising code) if they were also `Signal` properties like follows?

    ```swift
    public protocol ChangeEmailViewModelInputs {
      var emailFieldTextDidChange: Signal<String?, Never> { get }
      var saveButtonTapped: Signal<(), Never> { get }
    }

    public protocol ChangeEmailViewModelOutputs {
      var emailText: Signal<String, Never> { get }
    }

    public final class ChangeEmailViewModel /*...*/ {

      // MARK: - Input

      public let emailFieldTextDidChange: Signal<String?, Never>
      public let saveButtonTapped: Signal<(), Never>

      // MARK: - Output
      
      public let emailText: Signal<String, Never>
    }
    ```

1. I also see that on each 'input signals' (almost, if not all), the view model sets the received value (if any) to a `private *: MutableProperty<T>`. Why not make the input signal as `MutableProperty` right away?

    ```swift
    public protocol ChangeEmailViewModelInputs {
      var emailText: MutableProperty<String?> { get }
    }
    ```

1. Let's say if the inputs are `MutableProperty<T>`s, is it "bad" to process it and bind it straight to output? (by bad here, I mean bad practice, possible memory leaks, etc.)

    ```swift
    public final class ChangeEmailViewModel /*...*/ {
      // MARK: - Output
      
      public let formattedEmailText: Signal<String, Never>

      init() {
        // ...
        formattedEmailText <~ emailText.signal.map(doSomethingLikeFormatting(_:))
        // ...
      }
    }
    ```

I'm sure it's probably just me or there is some context that are not available just by studying the repository. Looking forward to any of your answers.

Thanks in advance!

**Comment by justinswart** [comment]
Hi @lifetimelearn3r, thanks for your questions.

1. The inputs are functions so that we can pass values to them. Perhaps you can explain a little more by what you mean when you say the inputs could also be properties? How would you go about passing values to those input `Signal`s?
2. We back our input functions with `MutableProperty`s to bridge the value into the ReactiveSwift world. It's also been our preference to abstract this away from the callsite. When we call inputs from our views all we care about is that we are passing a value to the view model and that we're observing any side-effect produced by that. We're not entirely interested in the fact that this value is being set on a `MutableProperty`. It's true that we could just set this directly but we feel our approach is cleaner. It could also be that in some scenario we might want to back our function with a pipe rather than a property and this would allow us to do so without breaking the convention of our protocol.
3. Binding in that way would be fine, I don't believe it would introduce leaks. However I think that in your example the `<~` operator would require `formattedEmailText` to be a `MutableProperty<String>` 🤔
