### ISSUE TITLE
why swizzle UIView & UIViewController?

### ISSUE THREAD

**Issue by AndrewSB** [kickstarter/ios-oss#162]
I'm trying to understand the tradeoff that was made when the decision to swizzle was made.

It seems to me that the objective in your swizzle was to remove your binding code from ViewControllers in your application and keep it in this arguably unsafe swizzled function instead.

Why not subclass instead? And do all of the binding in a `KickstarterViewController` or `BindingViewController`, and have your application VCs inherit from that subclass?

**Comment by stephencelis** [comment]
Thanks for the question!

That decision was made awhile ago, so it's not completely fresh, and @mbrandonw may remember more, but our goal was to create new, application-wide lifecycle events that we could use. Subclassing prevents us from using Apple's wider ecosystem of view controllers (`Table*`, `Collection*`, etc.), while swizzling allowed us to be sure that our lifecycle methods were called and we didn't have to think about it each time.

In the end, though, you bring up a good point: was swizzling worth it? While swizzling seems safe enough in code we own (third party libraries that swizzle are more likely to lead to unexpected situations and bugs), it's still an abstraction, and in this case we've used it to remove boilerplate. We've embraced boilerplate so many other places, that perhaps having an explicit pattern of view model and style bindings would have been fine!

**Comment by mbrandonw** [comment]
Yeah, I think the main goal was to not subclass at all costs so that we were never tempted down the road to adding more functionality to our base classes. It just felt like a slippery slope.

And I totally agree with Stephen. Were we to reconsider today, with everything we have learned, I think we would embrace the boilerplate of just manually adding `bindStyles`/`bindViewModel` to every VC and get rid of the swizzling! We have such good coverage and process around screenshot testing that we would very immediately catch anytime one of those things wasn't hooked up.

**Comment by AndrewSB** [comment]
> Yeah, I think the main goal was to not subclass at all costs so that we were never tempted down the road to adding more functionality to our base classes. It just felt like a slippery slope.

I can buy that, seems like a defensible trade-off. After being burned by third party libraries swizzling UIKit classes, I now take a long hard look at swizzles anywhere

Thank you for thoughtfully answering my question! Keep up the great work @stephencelis @mbrandonw 😄
