### ISSUE TITLE
Question: non-retina icons

### ISSUE THREAD

**Issue by bogren** [kickstarter/ios-oss#196]
Why do you still keep non-retina @1x icons around? As far as I understand you only support retina devices and those icons can be removed and excluded when adding new icons.

**Comment by justinswart** [comment]
@bogren I think we just have app icons @1x (ie. springboard icon), all of our in-app icons are universal vector shapes that we export as PDFs in Sketch and import into Xcode so that they can be rendered at any scale:

<img width="257" alt="screen shot 2017-07-06 at 2 10 55 pm" src="https://user-images.githubusercontent.com/3735375/27910337-0045414c-6255-11e7-909a-5c5ddf4414d9.png">

**Comment by bogren** [comment]
Ah 👍 I missed that part in the PR where I thought you exported PNGs.
